// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    ATMInfo: typeof import('./components/main-page/ATMInfo.vue')['default']
    ChatbotImageModal: typeof import('./components/chatbot/main/ChatbotImageModal.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FlyoutMenu: typeof import('./components/main-page/FlyoutMenu.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    InfoDialog: typeof import('./components/InfoDialog.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReplyMessage: typeof import('./components/chatbot/messages/ReplyMessage.vue')['default']
    ReplyMessageGroup: typeof import('./components/chatbot/messages/ReplyMessageGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMessage: typeof import('./components/chatbot/messages/UserMessage.vue')['default']
    UserMessageGroup: typeof import('./components/chatbot/messages/UserMessageGroup.vue')['default']
  }
}
